### ISSUE TITLE
Strong unforgeability of signatures

### ISSUE THREAD

**Issue by real-or-random** [zoom/zoom-e2e-whitepaper#13]
DualSign as currently specified in the paper is malleable because i) ECDSA is malleable ii) the DualSign construction allows "mix-and-match" if the attacker is able to get two signatures on the same message. 

I don't see how malleability hurts in the current design but it may be a good idea to be cautious and avoid malleability because it's a somewhat unexpected property and can lead to subtle issues (not only in the current design but also for future extensions).

Here are two ways that should achieve strong unforgeability:
 - First sign the message with ECDSA, then sign the message and the ECDSA signature with EdDSA. Note that used EdDSA variant from RFC 8032 is not malleable. 
 - Drop ECDSA and rely only on EdDSA (#11). The draft NIST variant of EdDSA is not malleable either.

**Comment by karanlyons** [comment]
That’s a good catch! We don’t rely on the ECDSA signature as a unique identifier and our verification operations require both the ECDSA and EdDSA signatures to verify correctly. Our plan is to remove the requirement for ECDSA when Curve25519 and EdDSA are formally approved by NIST.
