### ISSUE TITLE
Clarify user indices

### ISSUE THREAD

**Issue by real-or-random** [zoom/zoom-e2e-whitepaper#14]
The doc often says "user _i_" etc., and the _i_'s are also used in messages, e.g., included in hash computations. But it's not clear what these are. Are they numeric indices (if yes, who is responsible for enumerating users when they join one after another)? Are they account/user names?

**Comment by karanlyons** [comment]
_i_’s are indeed unique per user identifiers, though the precise identifier is yet to be determined.

**Comment by AnnaKornfeldSimpson** [comment]
How does user enumeration/identification work for "guest" attendees? Or are those not allowed, even in Phase 1?

**Comment by mmou** [comment]
All meeting attendees will create a device key that essentially identifies them. Some meeting attendees will, in addition, have their public key vouched for by their IdP, as outlined in Phase 2.
