### ISSUE TITLE
PKi needs to be stored to and fetched from key server

### ISSUE THREAD

**Issue by nickxiao-zoom** [zoom/zoom-e2e-whitepaper#15]
in 3.7.3
3. Computes bindingi ← (meetingID∥meetingUUID∥i∥deviceID∥IVKi ∥ pki).

the last component `pki` should be fetched from key server

**Comment by karanlyons** [comment]
PK<sub>i</sub> is the user’s ephemeral public key generated in 3.7.1 step 1, it’s posted to the bulletin board (as Sig<sub>i</sub>) and fetched by the leader in 3.7.3 step 2, but the contents of the bulletin board are not stored past the meeting, and this ephemeral key is not known to the keyserver hosting sigchains.
