### ISSUE TITLE
The author list does not state who Lea Kissner is affiliated with

### ISSUE THREAD

**Issue by nzall** [zoom/zoom-e2e-whitepaper#17]
I am not a cryptography expert and as such won't be commenting on the algorithms, protocols or other implementation details within this whitepaper. However, something I've noticed is that in the author list, everyone has a footnote stating the organization they're affiliated with. That is, everyone apart from Lea Kissner. Is there any particular reason why her affiliation was left out?

**Comment by JonHaas** [comment]
If I recall correctly, Lea is not presently affiliated with any organization, following the coronavirus impact on Humu. They are represented in their individual capacity, I believe.

**Comment by LeaKissner** [comment]
Precisely correct, @JonHaas . I am consulting with Zoom but am currently independent and thus did not list an affiliation.
