### ISSUE TITLE
Securing of Private and ephemeral Private Keys

### ISSUE THREAD

**Issue by sgel83** [zoom/zoom-e2e-whitepaper#18]
There is a no addressing in the documentation as to how the Private keys generated either by:

- DualSign.KeyGen
- Box.KeyGen

are secured.

Considering users corporate or personal machines are the easiest and most abundant channel to hijack the identity of a user securing the private keys should be addressed before Phase I rollout.

Private keys generated from the application should be secured and encrypted themselves.

In a Windows Environment which will make up most of the user base DPAPI should be used.
https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-use-data-protection

MacOS / IOS / Android / Linux applications should be using keyrings/keystores to protect the private key.

**Comment by karanlyons** [comment]
See #5.
