### ISSUE TITLE
Consider related work like Matrix / Signal / Double Rachet

### ISSUE THREAD

**Issue by nealmcb** [zoom/zoom-e2e-whitepaper#23]
The whitepaper should consider and cite related work like Signal's [Double Ratchet Algorithm](https://signal.org/docs/specifications/doubleratchet/), the [Matrix open standard](https://matrix.org/) for secure decentralized communications, etc. and explain what would motivate a different approach like Keybase's.

**Comment by mmou** [comment]
We think that the Double Ratchet protocol is fantastic, but it’s designed for asynchronous and persistent communications, which is a different model from ephemeral meetings with many-to-many high bandwidth data messages.
