### ISSUE TITLE
Is the leader ephemeral key supposed to be the one hashed to produce the Meeting Security Code?

### ISSUE THREAD

**Issue by dconnolly** [zoom/zoom-e2e-whitepaper#24]
The current document specifies the leaders' long-term public verifying key, meaning that the 'meeting code' will be the same for every meeting this leader hosts. If you hash the leader's ephemeral per-meeting public key, that will be different for every meeting this user hosts, but consistent for the whole duration of this meeting while hosted by this user, unless the ephemeral keypair changes or the leader is handed over.

![image](https://user-images.githubusercontent.com/552961/83290152-2d097080-a1b4-11ea-9ff9-893ce94360b2.png)

If this is the intended key, perhaps it's more accurate to call it a "Host Security Code" or even just "Host Fingerprint"? I know trust in the security of the meeting hinges on the leader/host being trusted, but having a 'meeting security code' be the same for every meeting a user hosts seems mis-named. 

If the meeting security code is _supposed_ to be about proving safety from MITM, it's also being used in a social context in the meeting: a mismatch is supposed to result in a re-key, but it seems like a false-positive (Abusive Andy confirming the code they saw in a different meeting by the same host, in front of the whole meeting, when they aren't supposed to be there) looks bad and reduces trust/care in the meeting security code at all.

Renaming this code to a 'Host Security Code' or 'Host Fingerprint' make it explicit what we are identifying and trusting, the host. If we don't trust the host of the meeting, we probably shouldn't trust the meeting either, both in current Zoom and after Phase I, so I think the intention of the name  'meeting security code' is effectively achieved.

**Comment by mmou** [comment]
Thank you for your careful reading of the paper! We will rename “meeting security code” to “meeting leader security code” in the next draft to more accurately describe its properties.

**Comment by AnnaKornfeldSimpson** [comment]
To follow up on this, if the leader changes during a meeting (e.g. the host passes leadership to a co-host), does that mean everyone's security code will change mid-meeting? If someone joins after the leadership changes and so the reading-out-loud ceremony must be repeated, is there a way to prevent existing meeting attendees from confusion that their security codes have changed?

**Comment by mmou** [comment]
If the leader changes during a meeting, then yes the meeting leader security code will change. Existing meeting attendees will need to recheck the meeting leader security code, since there is a new leader.
