### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by rjkrish** [zoom/zoom-e2e-whitepaper#27]
Review comments should not always be about shortcomings or potential improvements. So this is not really an "issue". Please go ahead and close it!

Having said that, 

thank you for sharing this in the public domain and adopting an open approach to designing secure software.

This a very well-written and very accessible spec. It's not only instructive, from an enterprise software design perspective, but also reassuring as Im a regular user of Zoom in my workplace like so many others.

Kudos to Zoom and the E2E team for providing clear visibility on this important topic.
----
Disclaimer: I do not work for Zoom. Opinions are my own and not my employer's.

**Comment by LeaKissner** [comment]
Thank you so much. We're so glad that this was helpful.
