### ISSUE TITLE
Alternatives to proprietary key management

### ISSUE THREAD

**Issue by anonyomelabs** [zoom/zoom-e2e-whitepaper#28]
This is a great start and solves a lot of problems for right now. We wanted to send feedback on some concepts to consider, particularly for the long-term. We believe that ultimately an open standards-based approach that can evolve with the community and adapt to new attacks and defenses will be key. Many of us spend a lot of time in the open standards community and I think the world has learned that transparency and openness – particularly when it comes to the application of cryptography – is essential. We believe an approach that is centered on decentralized identity and associated key management will stand the test of time and will also better protect Zoom, its customers and its users. A decentralized identity approach will be particularly important in pre-meeting key exchanges, user/customer privacy and in the security of content such as meeting recordings. We’ve put together some thoughts in the attached paper to consider.

Best,
Anonyome Labs
[Anonyome Response to Zoom E2E Whitepaper.pdf](https://github.com/zoom/zoom-e2e-whitepaper/files/4738756/Anonyome.Response.to.Zoom.E2E.Whitepaper.pdf)

**Comment by LeaKissner** [comment]
Thank you for your suggestion.
