### ISSUE TITLE
Dedicated security analysis for forward secrecy/post-compromise security

### ISSUE THREAD

**Issue by chelseakomlo** [zoom/zoom-e2e-whitepaper#3]
Many messaging protocols include analysis specifically for adversaries that can temporarily compromise the local state of a participant, and provide the capability for the protocol to be "self-healing" if such an event occurs. 

It would be helpful to see this kind of adversary described in the threat model and include analysis about how the protocol protects against such scenarios (and how this protection changes across each phase). While some analysis for forward secrecy is included (for example, it is discussed in Section 3.8.3), it would be helpful to see a more complete analysis of the circumstances under which forward secrecy/post-compromise security are preserved (after meeting teardown, after participants join/leave, etc).

**Comment by AMarcedone** [comment]
Thank you for your thoughtful question. We will update the document to add more details, but let me offer some preliminary comments.

Our current proposal relies on long term signing keys for the identity of each user. The current document does not consider rotating these long term keys and so, if these keys are compromised, an attacker will be able to join meetings on behalf of the user until the compromise is discovered and the compromised keys revoked. 
A security conscious user, or an organization with compliance requirements in this space, can always rotate their keys by revoking their current device and making a new one. In Phase IV, we will consider a mechanism for the old key to vouch for the validity of the new one during a rotation. Frequently rotating keys might pose a scalability challenge for the amount of data stored in the Transparency Tree, but we are investigating how to incorporate more frequent automatic rotations in the design.
