### ISSUE TITLE
XSalsa20 explanation

### ISSUE THREAD

**Issue by andrewaeva** [zoom/zoom-e2e-whitepaper#39]
Why XSalsa20 is used in Box.enc/dec?
Is there an explanation?

**Comment by oconnor663** [comment]
The main reason for using XSalsa20 in the whitepaper was that it's the cipher underlying NaCl's `crypto_secretbox`. But as we work on the early implementation, it's looking like we'll switch this to XChaCha20. That's becoming the more widely standardized version of the cipher, and it's the recommended AEAD construction in libsodium also.
