### ISSUE TITLE
Suggestion of alternate algorithm for randomness

### ISSUE THREAD

**Issue by mark-loveless** [zoom/zoom-e2e-whitepaper#4]
The current client software uses the underlying operating system for PRNG. I'd recommend using the ISAAC algorithm, which is fast and robust against attacks. I am unsure how this might impact the browser-based client, but the various clients including the those for mobile platforms could benefit from this.

**Comment by kwantam** [comment]
It's probably not a great idea to use an outdated and not-particularly-widespread cipher design for what is supposed to be a CSPRNG. If going the route of strengthening the system's prng, something based on AES or Salsa/ChaCha is a better choice, since one of those will presumably be the symmetric cipher that the system uses elsewhere.

**Comment by mark-loveless** [comment]
I am more than willing to concede to another CSPRNG, I mentioned ISAAC because of its amazing speed and the lack of "full breaks" as you accurately put it. Crypto and battery life on phones don't always get along, and so a lot of coders are unwilling to use much more than whatever the local device hands them. Here is an opportunity for them to step things up a bit.

Really as long as it is better than right now, I can live with it.

**Comment by oconnor663** [comment]
There are a number of randomness-related issues that only the OS can protect against. One is that a process might copy its RNG state by forking. Another is blocking during early boot until the kernel entropy pool has been properly seeded. These aren’t exactly common issues for a desktop application, sure, but crypto code has a tendency to get copied or linked into weird places over the years. So unless there’s a specific performance reason why the OS PRNG isn’t good enough, it’s usually a good idea to just use it and that’s why we’ve made that choice in this design. See also: https://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/
