### ISSUE TITLE
zoom.cn and zoom.us

### ISSUE THREAD

**Issue by hilt86** [zoom/zoom-e2e-whitepaper#40]
Will the Chinese version of Zoom receive the same security feature set slated for the International version? Also if a Zoom (International) user calls a user in mainland China using the Chinese version of Zoom, which features apply?

**Comment by hilt86** [comment]
Any updates on this @astamos et al?

**Comment by AMarcedone** [comment]
Thanks for your question. As this is unrelated to the cryptographic design, we will not be answering it here.

**Comment by hilt86** [comment]
Where can I get an answer if this is the wrong place to ask?
