### ISSUE TITLE
Local key security that don't have hardware based keychain

### ISSUE THREAD

**Issue by kiranszone** [zoom/zoom-e2e-whitepaper#42]
How are you planning to handle devices that don't have hardware based key chains, but only depend software based keychains ? There are certain Android devices and Windows systems that store keys on the file system.

**Comment by maxtaco** [comment]
Store the key on the regular file system then.

**Comment by kiranszone** [comment]
regular file system is not a secure.

**Comment by maxtaco** [comment]
I understand, but what can you do? Not allow E2E on the device? I think we need to do the best we can.

**Comment by kiranszone** [comment]
you can provide additional options to secure it. I have seen apps using pbkdf2 for providing additional security.

**Comment by kiranszone** [comment]
I know it's not great user experience to enter additional password or reuse password. it provides an option for end client an additional options to protect. I have seen lots of mobile malware targeting this kind of implementation.
