### ISSUE TITLE
Zoom  - Regulatory requirements  

### ISSUE THREAD

**Issue by kiranszone** [zoom/zoom-e2e-whitepaper#45]
How is zoom planning to handle Cryptography implementation and Key Management Systems in regulatory environment ? you have provided specific algorithms and libraries that might not meet cryptography regulations in certain countries and regions. How is Zoom planning to handle those scenarios ?

**Comment by AMarcedone** [comment]
Thanks for your question. We intend to offer end-to-end encryption meetings in every market around the world.  We keep open lines of communication with law enforcement, governments and regulators around the world and will continue to do so.
