### ISSUE TITLE
Zoom and FIPS certified Hardware Security Module

### ISSUE THREAD

**Issue by kiranszone** [zoom/zoom-e2e-whitepaper#46]
are there any plans to use FIPS certified Hardware Security Module(HSM) in the end-to-end architecture ?

**Comment by JKProductions1** [comment]
Yes idk exactly what it’s doing but I am learning and, and thanks for all the kind help

**Comment by AMarcedone** [comment]
Thanks for your question. We have no plans to use HSMs at the moment, except as described in Section 3.7.1 for certificate management. We remain open to the idea should a compelling application arise.
