### ISSUE TITLE
Zoom - Compromised devices

### ISSUE THREAD

**Issue by kiranszone** [zoom/zoom-e2e-whitepaper#48]
How's zoom app going to manage when device is comprised with malware or jailbroke or rooted, etc ? is zoom application going to automatically delete the local key store, when it identifies device has been comprised.

**Comment by 0xHaas** [comment]
I'm not entirely sure this is something Zoom would be able to ensure. While one can certainly assess device state against known-good device state, without runtime execution monitoring that cannot be augmented or interrupted (which is already getting into tricky territory), I'm not sure how this would be achieved.

**Comment by AMarcedone** [comment]
Our model assumes the user’s devices are trusted. We offer the ability for the user to revoke a device when this is no longer the case.
