### ISSUE TITLE
Typo in 3.5.2 Authenticated Public-Key Encryption

### ISSUE THREAD

**Issue by franziskuskiefer** [zoom/zoom-e2e-whitepaper#52]
Box.Dec in section 3.5.2 in v3 of the whitepaper says `ComputeK′←cryptoboxbeforenm(pkRBox,skSBox)` in step 2. It should be `ComputeK′←cryptoboxbeforenm(pkSBox,skRBox)`

**Comment by AMarcedone** [comment]
Thank you so much for pointing this out. It is now fixed.
