### ISSUE TITLE
How does E2E prevent a malicious Zoom server from masquerading as the meeting leader?

### ISSUE THREAD

**Issue by fefrei** [zoom/zoom-e2e-whitepaper#53]
There's a scenario in which I don't understand how the current E2E design, and the meeting leader security code, prevent a malicious Zoom server from performing a MitM attack.

Consider a scenario where two participants, A and B, want to meet (with A being the intended meeting host), and a malicious Zoom server wants to record the conversation. Let's assume that the actual host joins last, or both participants join simultaneously, so there is no long phase where the host expects to be alone in the meeting.
I get how the E2E design prevents the Zoom server from interfering with the security of the meeting _as long as one of the legitimate participants is the meeting leader_. However, in this scenario, let's assume that the malicious server takes the role of the meeting leader. Both A and B are joined to an existing meeting using the _Participant Join_ flow – but they enter different meetings, both of which have the malicious server as the leader. From this point on, the server forwards any audio and video between A and B.

How could A or B detect this scenario?

- The leader participant list is under control of the leader. Since the malicious server is the leader in both meetings, it is free to craft a LPL that indicates there are just two participants in the meeting: A or B, and itself, masquerading as the other user, respectively.
- The meeting leader security code is intended to detect any disagreement between who the participants believe to be the meeting leader. However, in this case, A and B actually agree on who the leader is: It's the malicious server, masquerading as the other legitimate participant. Both A and B see the same meeting leader security code, the hash over the public key of the malicious server.
- A stronger, more permanent binding between user identities and public keys could show A and B that the other user in their meeting is not their respective partner, but the malicious server, but this is not implemented in phase 1.
- Neither A nor B are the meeting leader. But (unless both have recorded their own meeting leader security code from previous meetings and noticed the current meeting leader security code is neither of them,) they cannot identify this is the case: The Zoom client UI does not indicate who the leader is.

The Zoom UI does show who the _host_ of the meeting is, and it appears that currently (i.e. in phase 1 only), the host and the leader must be the same client. Is this restriction enforced client-side?
If so, A could notice that to them, it looks like B, unexpectedly, is the host – but the Zoom UI says that to ensure security, you only need to compare the meeting leader security code, not validate whether one of the participants sees themself as the host.
If the identity between host and leader is not enforced client-side, the malicious server could even make A the host of the meeting despite A not being the leader, thwarting this means of detection.

Is there an error in my reasoning? Am I missing a way for A and B to detect this?

I assume that you've considered that scenario and properly defended against it – so please consider this issue as a request to clarify. Thanks!

**Comment by AMarcedone** [comment]
Thanks for your great question. 
Yes, we enforce on the client that the host and the leader are the same. We will clarify in the Zoom UI how it is important that the host/leader is the one who should read the code aloud (or otherwise communicate it) to other participants.

**Comment by fefrei** [comment]
Thanks for your reply! This should fix it, as in my scenario, no-one would feel responsible for reading the code.
I'd suggest that you add information about this host-leader-identity enforcement to the whitepaper – especially since this will change in phase 2 (where you'll probably have stronger defenses against this type of attack).
