### ISSUE TITLE
Zoom disabled screenshare on Arch Linux

### ISSUE THREAD

**Issue by bquast** [zoom/zoom-e2e-whitepaper#60]
Since a while I cannot use Zoom to screenshare on Wayland anymore, I use EndeavourOS (a continuation of Antegos, an Arch "installer". While this is completely Arch, the name has been modified, and Zoom changes it behaviour based on this.

> Can not start share, we only support Wayland on GNOME with Ubuntu 17 and above, Fedora 25 and above, Debian 9 and above, [...] Arch Linux, AnterGos, and Manjaro If your OS in not on the list, please use x11 instead.

The problem is that while I am using an Arch Linux OS, the installer has modified the name.  EndeavourOS is a continuation of AnterGos which *is* on the list even thought it is no longer developed.

![Screenshot from 2022-12-05 20-26-41](https://user-images.githubusercontent.com/2590349/205791513-5475c706-dfa1-44ca-ba45-051aa1d770c9.png)

Please make sure that Linux Zoom also accepts EndeavourOS since it is simply Arch Linux named differently.

**Comment by AMarcedone** [comment]
Thanks for reporting this. In this repository we only accept suggestions related to the Zoom Cryptography Whitepaper. Please refer to support.zoom.us or community.zoom.com for all other topics.
