### ISSUE TITLE
Mention of "Deep Fakes" without definition

### ISSUE THREAD

**Issue by huslage** [zoom/zoom-e2e-whitepaper#7]
I believe there is a common use of the term `Deep Fake technology` as mentioned in Phase II, but I think in this context it would be good to define it explicitly.

**Comment by AdriaanDeVos** [comment]
Could you provide other common uses of `Deep Fake Technology`? The only definition shown on the first page Google, and available on Wikipedia is: `Deepfakes are synthetic media in which a person in an existing image or video is replaced with someone else's likeness.`

I do not think there will be any misconception on the term `Deep Fake technology` when it is not explicitly defined in the whitepaper.

**Comment by mmou** [comment]
Thanks for the note, in our paper we use “deep fakes” to refer to manipulated and/or fabricated audio/video data that uses synthetic media techniques to replace the likeness of one person with another. In the context of video meetings, using  a “deep fake” (especially in real-time) of a participant could potentially deceive others about the identity of that participant.

-- Zoom E2E Team

**Comment by saxenauab** [comment]
You may want to refer to our paper below which covers exactly this attack, both using "shallow" and "deep" fake technology.

https://sites.uab.edu/saxena/files/2019/12/ss-ccs14-1.pdf

Wiretapping via mimicry: Short voice imitation man-in-the-middle attacks on crypto phones.
Maliheh Shirvanian, Nitesh Saxena.
In ACM Conference on Computer and Communications Security (CCS), November, 2014.
